# Default values for icebreaker-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/joluc/icebreaker-exporter
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9877

# Application specific configuration
config:
  vessels: "OTSO,KONTIO,POLARIS,URHO,SISU,VOIMA,FENNICA,NORDICA,ALE,ATLE,FREJ,ODEN,YMER,IDUN,KRONPRINS HAAKON,SVALBARD"
  refreshInterval: "2m"
  digitrafficUser: "icebreaker-exporter/1.0"

serviceMonitor:
  enabled: false
  namespace: ""
  interval: "2m"
  scrapeTimeout: "30s"
  additionalLabels: {}

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http
