apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "icebreaker-exporter.fullname" . }}
  labels:
    {{- include "icebreaker-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "icebreaker-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "icebreaker-exporter.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.config }}
          args:
            - "-vessel-names={{ .vessels }}"
            - "-refresh-interval={{ .refreshInterval }}"
            - "-digitraffic-user={{ .digitrafficUser }}"
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
